### ISSUE TITLE
adding example about how to use `geom_xsidehistogram`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [jtlandis/ggside#1]
Great package!

I am wondering if you can add an example to the documentation (either as an example in the manual or in the vignette) that shows how to use `geom_xsidehistogram`. 

I personally could not figure out how to use this particular `geom`, and it would be helpful to have an example to follow.

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

p <- ggplot(iris, aes(Sepal.Width, Sepal.Length)) + geom_point()

p + ggside::geom_xsidehistogram(aes(y = stat("bin")), binwidth = 0.1)
#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion

#> Warning in fun(x, ...): NAs introduced by coercion
#> Warning: Removed 25 rows containing missing values (geom_xsidebar).
```

![](https://i.imgur.com/TmQZ6gn.png)

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by jtlandis** [comment]
Hello! 
Thank you for bringing this to my attention. There are a few API styles that are still up in the air when it comes to using these types of functions. Currently the underlying ggproto object is confused because there is a global aesthetic mappings of `aes(x = Sepal.Width, y = Seapl.Length)` and yet traditionally a `geom_histogram` will only have one of these mapped and the missing value will be computed.

Thus, if you force `inherited params = F` then the resulting code should work:

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
p <- ggplot(iris, aes(Sepal.Width, Sepal.Length)) + geom_point()
p + ggside::geom_xsidehistogram(aes(x = Sepal.Width), binwidth = 0.1, inherit.aes = F)
```

![](https://i.imgur.com/FCErAA0.png)

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


Right now, `ggside` tries to keep all expressive control on the user. For example, one could have the `geom_xsidehistogram` oriented in the y direction (even though the resulting figure is confusing at best), but none the less doable. 
 
``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
ggplot(iris, aes(Sepal.Width, Sepal.Length)) +
    geom_point() +
    geom_xsidehistogram(aes(y = Sepal.Length),
                        binwidth = 0.1,
                        inherit.aes = F,
                        orientation = "y")
```

![](https://i.imgur.com/j6AWzTH.png)

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

 But this is undoubtable a bit confusing on what to expect. For some time now I have debated on how to approach the case that when having a global mapping, and using any `geom_xside*` function that will typically compute its own y aesthetic mapping while inheriting by default from the x global aesthetic mapping. It may be possible to to get this working by default. This is a feature I do want to add, as `geom_xsidehistogram` is not the only function with this type of heuristic. Unfortunately, I haven't yet found the solution that works.

This is definitely a feature improvement that will be added eventually, but in the meantime I will try to include an example for each of the `ggside` layer functions as a hotfix.

**Comment by IndrajeetPatil** [comment]
Oh, I see!

Got it. Thanks a lot for this amazing work. 

Your R package is a bona fide hit on [Twitter](https://twitter.com/patilindrajeets/status/1367019279963607045?s=20) 😉

**Comment by jtlandis** [comment]
Currently, more documentation has been added to `ggside v0.0.2` which is the master branch of this github. CRAN will not allow me to update the package until at least a month as passed. The release of `ggside v0.0.3` is tentatively scheduled for mid April which will include the documentation changes as well as a few other things.
