### ISSUE TITLE
ggside modifies class, making it incompatible with patchwork

### ISSUE THREAD

**Issue by DominiqueMakowski** [jtlandis/ggside#13]
ggside geoms add a primary `ggside` class, which makes it incompatible with other methods, such as patchwork's.

``` r
library(ggplot2)
library(ggside)
library(patchwork)

p1 <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point(size = 2) +
  geom_xsidedensity()

p2 <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point(size = 2)

p1 + p2
#> Error in match(x, table, nomatch = 0L): 'match' requires vector arguments
```

One current workaround is to manually drop the `ggside` class.

``` r
class(p1) <- class(p1)[class(p1) != "ggside"]
p1 + p2
```

![](https://i.imgur.com/PuTV4uT.png)

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

As a general fix, I'm not sure that ggside geoms should modify the plot's class (at least not the primary one), as it could have unexpected downstream consequences.

**Comment by jtlandis** [comment]
I think I know what the issue is, and its an unfortunate issue that is slightly related to an issue in [ggplot2](https://github.com/tidyverse/ggplot2/issues/3986). The basis being that my package, in order to make it consistent, requires me to overwrite `+.gg` method to use an internal `add_gg` S3 method to control how things are added to my new `ggside` class. For instance, the issue I was running into was, if a `(x|y)side` layer was added, and then a `facet` layer was added, my object would not be built correctly without the overwrite (`ggside`'s magic comes from modifying the base facet methods).

There were other ways to get around this, like writing my own `ggplot_build.ggside` method, but I avoided this because I wanted my package to be compatible with `gganimate`. So this came down to a preference of compatibility and I think there will usually be some conflicts between different `ggplot2` package extensions.

That being said, I believe this could be remedied. After a bit of digging I located the issue - 
currently what is being called when you use `p1 + p2` is `ggside:::"+.gg" -> ggside:::add_gg.ggside `

As of `ggside v0.1.0` `add_gg.ggside()` is defined as following
```r
add_gg.ggside <- function(e1, e2, e2name) {
  p <- NextMethod("add_gg")
  if(!(is.ggside_layer(e2)|is.ggside_options(e2)|is.ggside_scale(e2)|is.ggplot(e2))){
    p <- as_ggside(p, e2)
  }
  p
}
```

I had compatibility in mind when making this package. The `NextMethod()` function here ensures that `add_gg.ggplot` will be called which just calls `ggplot_add` (the default S3 API of `ggplot2`). So, if you were to look at `p` right after the `NextMethod` was called, then you would see the patchwork being made properly.

The conflict comes from `as_ggside` function, which assumes that `p` is a vanilla `ggplot` object and not a `patchwork` object.

A quick fix would be to make it so `as_ggside` isn't called if e2 is a `ggplot` object. The following code shows what that would look like in a quick build.

``` r
library(ggplot2)
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
library(patchwork)


p1 <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point(size = 2) +
  geom_xsidedensity()

p2 <- ggplot(mpg, aes(displ, hwy, colour = class)) +
  geom_point(size = 2)


p1 + p2
```

![](https://i.imgur.com/AJTE5Hd.png)

<sup>Created on 2021-06-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


I think I will ultimately change how this function is called because the ONLY case when it needs to be called is if the right hand object is a `Facet` object or a `Coord` object.

**Comment by jtlandis** [comment]
As a note for my future self, the merge #14 fix to this issue does not take the rewrite suggested in my post. Instead I make an internal S3 function called `validate_ggside` which will be called in `add_gg.ggside`. It takes two arguments, `e2` and `object`. It will dispatch on `e2` (right hand side of the `+`) and the default will just return `object`. If `e2` inherits from `"Facet"` class then `object` will be returned with the proper adjustments to make it a proper `ggside` object.
