### ISSUE TITLE
titles for side panels?

### ISSUE THREAD

**Issue by aghaynes** [jtlandis/ggside#22]
It strikes me that `ggside` is a super way to construct KM curves, in particular the risk table. `survminer` is ok, but customizing the plot can a bit tedious... `ggside` would let the user have more control...

So it would be good to be able to put a title on the side panel somewhere/somehow. Is that possible at all?

``` r
library(survival)
leukemia.surv <- survfit(Surv(time, status) ~ x, data = aml) 
plot(leukemia.surv, lty = 2:3)
```

![](https://i.imgur.com/QqS1Bt7.png)

``` r
# ok, but no risk table

# couple of functions for collecting necessary info from surv objects
as.data.frame.survfit <- function(x){  
  s <- do.call("c", lapply(seq_along(x$strata), function(i) rep(names(x$strata)[i], x$strata[i])))
  data.frame(strata = s,
             time = x$time,             
             n.risk   = x$n.risk  ,              
             n.event  = x$n.event ,              
             n.censor = x$n.censor,              
             surv     = x$surv    ,              
             std.err  = x$std.err ,              
             upper    = x$upper   ,              
             lower    = x$lower    )  
}
as.data.frame.summary.survfit <- function(x){  
  data.frame(strata = x$strata,
             time = x$time,             
             n.risk   = x$n.risk  ,              
             n.event  = x$n.event ,              
             n.censor = x$n.censor,              
             surv     = x$surv    ,              
             std.err  = x$std.err ,              
             upper    = x$upper   ,              
             lower    = x$lower    )  
}

sdf <- as.data.frame(leukemia.surv)
sdf2 <- as.data.frame(summary(leukemia.surv, times = c(0, 25, 50)))

library(ggplot2)
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

ggplot(sdf, aes(x = time, y = surv, col = strata)) +
  geom_step() +
  geom_xsidetext(aes(label = n.risk, x = time, y = strata), 
                 data = sdf2,
                 key_glyph = "blank",
                 col = "black") +
  scale_xsidey_discrete() +
  ggside(x.pos = "bottom")
#> Warning in Ops.factor(x, range[1]): '<' ist nicht sinnvoll für Faktoren
#> Warning in Ops.factor(x, range[2]): '>' ist nicht sinnvoll für Faktoren
```

![](https://i.imgur.com/YpsNmGn.png)

<sup>Created on 2021-07-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by aghaynes** [comment]
Also, is there way to move the axis between the plot and the side panel perhaps? that would give the overall thing a more typical KM curve appearance...

**Comment by jtlandis** [comment]
I thought it was only a matter of time before someone asks for a second axis label. The main reason why I haven't put too much thought into it is because I would have no idea how this would work in relation to `facet_wrap()` and `facet_grid()` when `ggside(collapse = NULL)`. Additionally, I don't exactly know how much of an undertaking it would be to position the text grobs such that the main title is centered on the main panel axis and the side panel title is centered on the side panel axis.

With all this being said, I think your second request is probably doable. The logic that handles when/where the axis guides are drawn happens in the `$draw_panels` method. 
Here is my initial thoughts on how this would work. I can add two additional arguments to the `ggside` function, `draw_x_axis_on`, `draw_y_axis_on`, whose default values will be `"default"`. The default behavior of `ggside` is to place the axis guides (for the x axis) on the bottom most/top most panel per panel group, depending on what the 'position' argument is set for that scale. The `draw_x_axis_on` if set to `"main"` could render the axis next to the the main panel, either on top or on bottom, or if set to "side" will render the axis on top or on bottom of the xside panel.

**Comment by jtlandis** [comment]
In regards to your first request, depending on how you use `guide_axis` with `scale_(x|y)side(y|x)_*()`, you can get the feel you want:

``` r
library(ggside)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
ggplot(mpg, aes(displ, hwy)) + 
  geom_point() + 
  geom_xsideboxplot(aes(y = class), orientation = "y") +
  scale_xsidey_discrete(position = "right", guide = guide_axis("TEST")) +
  theme(axis.title.y.right = element_text(hjust = .05),
        ggside.panel.scale = .20)
```

![](https://i.imgur.com/ZfIeqPB.png)

<sup>Created on 2021-07-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Unfortunately, this does not work with `ggside(x.pos = "bottom")` and I do not know why to be honest. This is probably quite hacky, but is the best this package can do at this point.

I'd recommend using `cowplot` and just plot 2 plots together. I think that would be the best way to get the feel you are asking for in your original post.

**Comment by aghaynes** [comment]
Thanks for thinking about this 😃

**Comment by jtlandis** [comment]
Hello! I've recently gotten inspiration to work on the package again. I've been looking into the practicality of this request, specifically adding another title to the axis. Currently this is handled by the `Layout` object with the `render_labels()` method. Unfortunately, modifying the `Layout` object is currently outside the scope of the `ggside` package simply because that would require `ggside` to make its own `ggplot_build.ggside` method (which may affect how compatible `ggside` is with other `ggplot2` package extensions).

For now I think I will close this issue as a won't fix and open another in its place for allowing axis to be rendered in-between plots.

**Comment by aghaynes** [comment]
OK. Thanks for thinking about this still!
