### ISSUE TITLE
ggsides don't work if aesthetic mapping passed directly

### ISSUE THREAD

**Issue by DominiqueMakowski** [jtlandis/ggside#31]
Think 'tis a bug; it seems like if the `aes` are passed directly to the geom, it doesn't work 😞 

``` r
library(ggplot2)
library(ggside)
#> Warning: package 'ggside' was built under R version 4.1.3
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

ggplot(mtcars, aes(x = mpg, y = wt)) +
  geom_point() +
  ggside::geom_ysidedensity()
```

![](https://i.imgur.com/DgE9RvU.png)

``` r
ggplot(mtcars) +
  geom_point(aes(x = mpg, y = wt)) +
  ggside::geom_ysidedensity(aes(x = mpg))
#> Warning: Groups with fewer than two data points have been dropped.
#> Error in `check_required_aesthetics()`:
#> ! geom_ysidedensity requires the following missing aesthetics: x
```

![](https://i.imgur.com/bZ3Dee5.png)

<sup>Created on 2022-03-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jtlandis** [comment]
Question, is this error in the development version of `ggside` or the CRAN version?

**Comment by jtlandis** [comment]
I just confirmed that it is in both. Thank you for reporting this issue, it is definitely unintentional.

**Comment by jtlandis** [comment]
``` r
library(ggplot2)
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2
p <- ggplot(mtcars) + geom_point(aes(x = mpg, y = wt))
```

I have found the core of this issue. The following chunk does not work
but it was an intentional feature implemented early in `ggside`’s development.

Here we are assigning the `x` aesthetic to the `yside` geom\_density variant.
This function is typically intended to have a density distribution calculated
on the `y` positional aesthetic and the `x` positional aesthetic is
a calculated statistic. Thus the below usage is a typical

``` r
p + ggside::geom_ysidedensity(aes(x = mpg))
#> Warning: Groups with fewer than two data points have been dropped.
#> Error in `check_required_aesthetics()`:
#> ! geom_ysidedensity requires the following missing aesthetics: x
```

![](https://i.imgur.com/bDkkqLV.png)

We can however directly assign `aes` in a way `ggside` expects reletive to
the `xside` or `yside` variant

``` r
p + ggside::geom_ysidedensity(aes(y = wt))
```

![](https://i.imgur.com/G8xcFzt.png)

If you really wish for `aes(x = mpg)` to be plotted, you need to tell the
layer the orientation with `orientation = 'x'`

``` r
p + ggside::geom_ysidedensity(aes(x = mpg), orientation = "x")
```

![](https://i.imgur.com/WBbF3JS.png)

I will admit, the error message is a bit unhelpful so I could probably
include a check in layers where orientation matters, but exactly how to do it
I am not yet certain.

The true issue in the first example is that the `y` aesthetic is missing.
I believe most geoms do eventually require both positional aesthetic mappings
with the exception of abline, vline, and hline.

<sup>Created on 2022-03-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
