### ISSUE TITLE
how to specify a fixed order for geom_ysideboxplots

### ISSUE THREAD

**Issue by hcuve** [jtlandis/ggside#43]
thanks for such a useful package.

I am plotting a few different panels where for ease of understanding I need the side boxplots to be in the same order, but ggside seems to always choose a specific order from a low value to the highest value.

Is there any way to specify this directly in ggside.

**Comment by jtlandis** [comment]
Hi, could you please provide a small reprex? (ideally using the reprex package) This way you can show me what you are looking for.

Here are my recommendations before I have seen your data.

``` r
library(ggplot2)
library(ggside)
#> Registered S3 method overwritten by 'ggside':
#>   method from   
#>   +.gg   ggplot2

p <- ggplot(iris, aes(Sepal.Width, Sepal.Length)) +
  geom_point() 
```

Typically, the order of the labels of a discrete scaled is determined by the if the data is a factor or otherwise. If it is a factor, the order is by the factor levels. Otherwise it will order the labels alphebetically
The `iris` dataset has the `Species` column as a factor already and this is the result

``` r
p + geom_ysideboxplot(aes(x = Species), orientation = "x") +
  scale_ysidex_discrete(guide = guide_axis(angle = 90))
```

![](https://i.imgur.com/R0jNmN6.png)

You can also simple change the order of the original data and pass it into the layer.

``` r
p + geom_ysideboxplot(aes(x = Species), orientation = "x",
                      #You may change the data directly or pass a function to the argument
                      # that changes the global data. Here I am using an `rlang` lambda function
                      # along with the `dplyr` and `forcats` package to reverse the factor levels
                      data = ~dplyr::mutate(.x, Species = forcats::fct_rev(Species))) +
  scale_ysidex_discrete(guide = guide_axis(angle = 90))
```

![](https://i.imgur.com/ljpkalI.png)

<sup>Created on 2022-12-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jtlandis** [comment]
I will be closing this issue since there hasn't been much discussion. I am going to assume that I have answered your question. If not, please feel free to leave a comment on this page.
