### ISSUE TITLE
Issues with the next release of scales

### ISSUE THREAD

**Issue by thomasp85** [jtlandis/ggside#49]
I'm reaching out because we plan to release a new version of scales in 2 weeks and our tests shows that ggside fails its unit tests with the new version. We hope you'll be able to work out a fix and please let me know if the root cause seems to indicate an issue in scales

best
Thomas

**Comment by jtlandis** [comment]
Thank you for reaching out, I will look into the issue this weekend. I have been a bit busy to delve into the development sphere as of late with graduate work.

**Comment by jtlandis** [comment]
After looking into it, my package is only failing because the `scales` mapping error changed from "date_trans works with objects of class Date only" to "`transform_date()` works with objects of class <Date> only"

I can make these changes relatively simply - Thanks for bringing this to my attention again!

**Comment by jtlandis** [comment]
ggside v0.2.3 is now compatible with the most recent version of scales :+1:
